version: "2"

linters:
  default: none
  enable:
    - misspell
    - govet
    - ineffassign
    - staticcheck
    - errcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - io.Copy
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    misspell:
      locale: US
  exclusions:
    generated: strict
    paths:
      - pkg/rpc
      - pkg/argon2
      - pkg/s3select/internal/parquet-go
      - pkg/s3select/internal/parquet-go/gen-go
      - pkg/s3select/internal/parquet-go/tools
      - pkg/smart/bindata.go
      - pkg/mimedb/util
      - _gen_test\.go
      - _gen\.go
    rules:
      - text: "should have a package comment"
        linters:
          - staticcheck
      - text: "error strings should not be capitalized or end with punctuation or a newline"
        linters:
          - staticcheck
      - path: _test\.go
        linters:
          - errcheck
      - text: "Error return value is not checked"
        linters:
          - errcheck

formatters:
  enable:
    - goimports
    - gofmt
  exclusions:
    paths:
      - pkg/rpc
      - pkg/argon2
      - pkg/s3select/internal/parquet-go
      - pkg/s3select/internal/parquet-go/gen-go
      - pkg/s3select/internal/parquet-go/tools
      - pkg/smart/bindata.go
      - pkg/mimedb/util
