version: "2"

linters:
  default: none
  enable:
    - misspell
    - govet
    - ineffassign
    - staticcheck
  settings:
    misspell:
      locale: US
  exclusions:
    generated: strict
    paths:
      - pkg/rpc
      - pkg/argon2
      - pkg/s3select/internal/parquet-go/gen-go
      - pkg/s3select/internal/parquet-go/tools
      - pkg/smart/bindata.go
      - pkg/mimedb/util
    rules:
      - text: "should have a package comment"
        linters:
          - staticcheck
      - text: "error strings should not be capitalized or end with punctuation or a newline"
        linters:
          - staticcheck

formatters:
  enable:
    - goimports
    - gofmt
  exclusions:
    paths:
      - pkg/rpc
      - pkg/argon2
      - pkg/s3select/internal/parquet-go/gen-go
      - pkg/s3select/internal/parquet-go/tools
      - pkg/smart/bindata.go
      - pkg/mimedb/util
