FROM ubuntu:24.04

LABEL maintainer="PGG Inc <oss@pgg.net>"

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends --no-install-suggests \
      git golang make npm && \
    apt clean && rm -rf /var/lib/apt/lists/*

ENV PATH=$PATH:/root/go/bin

RUN go get github.com/go-bindata/go-bindata/go-bindata && \
    go get github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs
