blank_issues_enabled: false
contact_links:
  - name: Obstor Community Support
    url: https://pgg.net/discord
    about: Join here for Community Support
  - name: Obstor SUBNET Support
    url: https://pgg.net/pricing
    about: Join here for Enterprise Support
