blank_issues_enabled: false
contact_links:
  - name: ObStor Community Support
    url: https://discord.pgg.net
    about: Join here for Community Support
  - name: ObStor SUBNET Support
    url: https://pgg.net/pricing
    about: Join here for Enterprise Support
